algo = input('Digite algo : ')
print('O tipo primitivo desse valor é: {}'.format(type(algo)))
print('So tem espaco: {}'.format(algo.isspace()))
print('È numerico: {} '.format(algo.isnumeric()))
print('É alphabetico: {} '.format((algo.isalpha())))
print('É alphanumerico {} '.format(algo.isalnum()))
print('Esta em maiuscula: {} '.format(algo.isupper()))
print('Esta em minuscula: {} '.format(algo.islower()))
print('Esta captalizada: {} '.format(algo.istitle()))