print('''Crie um programa que leia o nome completo de uma pessoa e mostre: ''')
print('O nome com todas as letras maiusculas: ')
print('O nome com todas as letras minusculas: ')
print('Quantas letras ao todo (sem considerar espaco)')
print('Quantas letras os primeiros nome tem')

nome = str(input('Digite seu nome: ')).strip()
print('ANALISANDO SEU NOME')
print('Seu nome em letras maiusculas é {}'.format(nome.upper()))
print('Seu nome eme letras minusculas é {}'.format(nome.lower()))
print('Seu nome ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
